services:
  - type: web
    name: osrs-bingo-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
